Repository flora-pm/flora-server, pull requests merged in 2022-10, with the labels that each got.

#229 [NO-ISSUE] Refine category normalisation
  .github/mergify.yml
  cbits/categorise.dl
Labels: squash+merge me

#230 [NO-ISSUE] Increase chunk size for package import
  src/Flora/Import/Package/Bulk.hs
Labels: squash+merge me

#231 [NO-ISSUE] Prepare v1.0.4
  CHANGELOG.md
  flora.cabal
Labels: squash+merge me

#232 [NO-ISSUE] v1.0.4
  .github/mergify.yml
  .github/workflows/check-flora-tickets-in-prs.yaml
  .github/workflows/check-ticket-in-prs.sh
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  assets/css/app.css
  assets/css/variables.css
  assets/package.json
  assets/yarn.lock
  cbits/categorise.dl
  deployment/flora.nginx
  design/stories/package-list--item.stories.js
  flora.cabal
  ghc-tags.yaml
  src/Flora/Import/Package/Bulk.hs
  src/FloraWeb/Components/Navbar.hs
  src/FloraWeb/Server.hs
  src/FloraWeb/Server/Auth.hs
  src/FloraWeb/Server/Auth/Types.hs
  src/FloraWeb/Server/Pages/Packages.hs
Labels: merge me

#234 [FLORA-233] Reorder the columns of the package view in mobile view
  CHANGELOG.md
  assets/css/app.css
  src/FloraWeb/Server.hs
  src/FloraWeb/Templates/Error.hs
Labels: squash+merge me

#236 [FLORA-205] Enable the use of markdown extensions
  CHANGELOG.md
  src/Flora/OddJobs.hs
Labels: squash+merge me

#241 [FLORA-147] Support release changelogs
  CHANGELOG.md
  assets/css/app.css
  assets/css/release-changelog.css
  assets/css/release-readme.css
  assets/css/variables.css
  flora.cabal
  migrations/20221011215519_add_changelogs.sql
  src/Flora/Import/Package.hs
  src/Flora/Model/Release/Query.hs
  src/Flora/Model/Release/Types.hs
  src/Flora/Model/Release/Update.hs
  src/Flora/OddJobs.hs
  src/Flora/OddJobs/Render.hs
  src/Flora/OddJobs/Types.hs
  src/Flora/ThirdParties/Hackage/API.hs
  src/Flora/ThirdParties/Hackage/Client.hs
  src/FloraWeb/Links.hs
  src/FloraWeb/Routes/Pages/Admin.hs
  src/FloraWeb/Routes/Pages/Packages.hs
  src/FloraWeb/Server.hs
  src/FloraWeb/Server/Pages/Admin.hs
  src/FloraWeb/Server/Pages/Packages.hs
  src/FloraWeb/Templates/Admin.hs
  src/FloraWeb/Templates/Packages/Changelog.hs
  src/FloraWeb/Templates/Pages/Packages.hs
  test/Flora/OddJobSpec.hs
Labels: squash+merge me

#242 [FLORA-208] Packages are no longer kept as their own dependent
  CHANGELOG.md
  migrations/20211113195849_create_dependents.sql
  test/Flora/PackageSpec.hs
Labels: merge me

#244 [FLORA-243] Only show library dependencies that are fully imported
  CHANGELOG.md
  migrations/20211106123053_create_releases.sql
  migrations/20221011215519_add_changelogs.sql
  src/Flora/Model/Package/Query.hs
  test/fixtures/Cabal/flora.cabal
Labels: squash+merge me

#245 [FLORA-185] Display license in package listings
  CHANGELOG.md
  app/cli/DesignSystem.hs
  assets/css/app.css
  assets/css/variables.css
  migrations/20220326182257_create_latest_versions.sql
  src/Flora/Model/Package/Query.hs
  src/Flora/Search.hs
  src/FloraWeb/Components/PackageListItem.hs
  src/FloraWeb/Templates/Packages/Dependencies.hs
  src/FloraWeb/Templates/Packages/Dependents.hs
  src/FloraWeb/Templates/Packages/Listing.hs
  src/FloraWeb/Templates/Pages/Categories/Show.hs
  src/FloraWeb/Templates/Pages/Search.hs
Labels: merge me

#247 [FLORA-246] Display package flags
  CHANGELOG.md
  assets/css/app.css
  src/Distribution/Orphans.hs
  src/Flora/Import/Package.hs
  src/Flora/Model/Release/Types.hs
  src/FloraWeb/Templates/Pages/Packages.hs
Labels: squash+merge me

#248 [FLORA-137] Render description to HTML when there is no README
  CHANGELOG.md
  assets/css/release-readme.css
  flora.cabal
  src/FloraWeb/Templates/Haddock.hs
  src/FloraWeb/Templates/Pages/Packages.hs
  test/Flora/PackageSpec.hs
  test/Flora/TestUtils.hs
  test/fixtures/Cabal/filepath.cabal
  test/fixtures/Cabal/relude.cabal
Labels: squash+merge me

#251 [NO-ISSUE] Prepare release 1.0.5
  CHANGELOG.md
  cabal.project.freeze
  flora.cabal
Labels: merge me

#252 [NO-ISSUE] Switch flake.nix to use horizon-platform at ghc 9.4.2
  flake.lock
  flake.nix
  nix/envparse.nix
  nix/log-effectful.nix
  nix/odd-jobs.nix
  nix/pg-transact-effectful.nix
  nix/prometheus-client.nix
  nix/prometheus-metrics-ghc.nix
  nix/raven-haskell.nix
  nix/servant-effectful.nix
  nix/time-effectful.nix
  nix/wai-middleware-heartbeat.nix
  nix/wai-middleware-prometheus.nix
Labels: squash+merge me

#256 [FLORA-255] Fix the `dependents` view to include other namespaces
  CHANGELOG.md
  environment.test.sh
  ghc-tags.yaml
  migrations/20211113195849_create_dependents.sql
  test/Flora/PackageSpec.hs
  test/Flora/TestUtils.hs
  test/Main.hs
Labels: squash+merge me

#259 [FLORA-258] Add new categories: profiling, debugging and telemetry 🆕
  CHANGELOG.md
  cbits/categorise.dl
Labels: squash+merge me, hacktoberfest-accepted

#261 [FLORA-260] Improve the listing of package versions
  CHANGELOG.md
  flora.cabal
  src/FloraWeb/Components/PackageListItem.hs
  src/FloraWeb/Components/VersionListItem.hs
  src/FloraWeb/Templates/Packages/Versions.hs
Labels: squash+merge me

#262 [FLORA-254] Use Sub-Resource Integrity (SRI) for JS and CSS
  .github/workflows/backend.yml
  CHANGELOG.md
  cabal.project.freeze
  flora.cabal
  src/Flora/Model/Package/Types.hs
  src/FloraWeb/Assets.hs
  src/FloraWeb/Components/Header.hs
Labels: squash+merge me

#266 [FLORA-254] Hash asset files for production builds
  CHANGELOG.md
  app/cli/DesignSystem.hs
  app/cli/Main.hs
  assets/css/styles.css
  assets/esbuild.config.js
  assets/package.json
  assets/postcss.config.js
  assets/yarn.lock
  cabal.project
  design/.storybook/preview.js
  design/styles.css
  flora.cabal
  src/Flora/Environment.hs
  src/Flora/Environment/Config.hs
  src/FloraWeb/Assets.hs
  src/FloraWeb/Components/Header.hs
  src/FloraWeb/Server.hs
  src/FloraWeb/Templates.hs
  src/FloraWeb/Templates/Types.hs
Labels: squash+merge me
