Repository flora-pm/flora-server, pull requests merged in 2024-10, with the labels that each got.

#603 [NO-ISSUE] Fix "Start with Cabal" link
  src/web/FloraWeb/Pages/Templates/Screens/Home.hs
Labels: bug, frontend

#763 Style: Fix fail CSS tokens nesting level
  assets/style-tokens/colors.json
  assets/style-tokens/fonts.json
  design/stories/package-list--item.stories.js
Labels: frontend

#764 Add “docker compose stop” task to Makefile
  Makefile
Labels: enhancement, Docker, Hackathon
